name: BuildTest_05_01

on:
  push:
    branches: 05_01

env:
  SOLUTION_FILE_PATH: sln\PG3.sln
  CONFIGURATION: Release

jobs:
  Build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}

