name: BuildTest_master

on:
  push:
    branches: master

env:
  SOLUTION_FILE_PATH: sln\PG3.sln
  CONFIGURATION: Release

jobs:
  Build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add MSBuild to Path
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}

      - name: Run
        run: |
          & sln\x64\Release\Project.exe
